### ISSUE TITLE
Failed to execute 'animate' on 'Element': 'tw-k' is not a valid value for easing

### ISSUE THREAD

**Issue by MarvinMiles** [sonofmagic/tailwindcss-mangle#21]
Hey!
Thank you for your amazing job. Works almost perfect out of box without any configured options. 

I'm using Vite/Vue and my first issue is:

**Input:**
<img width="501" alt="Screen Shot 2023-06-07 at 01 54 41" src="https://github.com/sonofmagic/tailwindcss-mangle/assets/1912057/e2a46a60-5e14-47e1-8a83-8880dae8a8f5">

**Bundled output:**
<img width="536" alt="Screen Shot 2023-06-07 at 01 57 55" src="https://github.com/sonofmagic/tailwindcss-mangle/assets/1912057/ca950bef-fb03-4ad0-8e74-d307c55603d0">

**This causing an issue:**
<img width="493" alt="Screen Shot 2023-06-07 at 02 10 31" src="https://github.com/sonofmagic/tailwindcss-mangle/assets/1912057/ea0fcddd-7e11-4af2-810b-b30c40e765ff">

Moreover, setting "ignoreClass" option in "classGenerator" has no effect. Is it WIP?

**Comment by sonofmagic** [comment]
Hello, the reason for this problem is that `ease-out` is also one of the class keywords generated by tailwindcss.

F.Y.I: https://tailwindcss.com/docs/transition-timing-function

so you can do this steps to fix this issue.

1: Upgrade to `unplugin-tailwindcss-mangle@1.2.2`

Then add some class not to be mangled
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { vitePlugin as utwm, defaultMangleClassFilter } from 'unplugin-tailwindcss-mangle'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    utwm({
      mangleClassFilter(className) {
        if (['ease-out', 'ease-linear', 'ease-in', 'ease-in-out'].includes(className)) {
          return false
        }
        return defaultMangleClassFilter(className)
      },
    })
  ]
})
```

**Comment by MarvinMiles** [comment]
It works now. Thank you!
