### ISSUE TITLE
JS bundle size increased

### ISSUE THREAD

**Issue by MarvinMiles** [sonofmagic/tailwindcss-mangle#22]
Hello!
I'm using Vite for my small Vue App.

"tailwindcss-patch" and "unplugin-tailwindcss-mangle" packages installed as Dev Dependencies.

Here is my vite.config.js before adding utwm() plugin:

```
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    target: 'es2015',
    },
  },
})

```
Output:
225.39 kB │ gzip: 74.91 kB

With utwm() plugin:
316.63 kB │ gzip: 84.25 kB

After some investigation, I found that the bundle contains white spaces. Looks like Vite bypassing minification process. Or, most probably, utwm plugin rewrites output source code, reversing minification.

Is this expected behavior?

Hard-coded `build.minify: 'esbuild'` option had no effect. Is there a simple solution for this?
Thank you.

**Comment by sonofmagic** [comment]
This issue has been solved in `1.2.2`.

Now When `process.env.NODE_ENV === 'production'`, Then plugin will minified js by default.

or you can pass `jsHandlerOptions` to control this behaviour:

```ts
utwm({
      jsHandlerOptions: {
        minified: false / true
      }
})
```
