### ISSUE TITLE
Bug with utility class which contains trailing slash

### ISSUE THREAD

**Issue by MarvinMiles** [sonofmagic/tailwindcss-mangle#24]
Hello!
I have last strange bug I faced with.

Vite+Vue

Reproduction link: https://replit.com/@MarvinMiles/css-mangle-bug.

During dev:
<img width="304" alt="Screen Shot 2023-06-07 at 14 59 11" src="https://github.com/sonofmagic/tailwindcss-mangle/assets/1912057/478002a8-e0c4-42cc-bfbf-3c80feeea8ad">

During preview after build:
<img width="308" alt="Screen Shot 2023-06-07 at 15 01 38" src="https://github.com/sonofmagic/tailwindcss-mangle/assets/1912057/63289c6d-52d9-4d3b-b6b3-a128d3fc4008">

`bg-red-500/50` transformed into`tw-g/50` and output CSS file does not contain that class.

It was hard to reproduce. Bug appears at strange conditions. For example, removing parent div makes it work properly.

**Comment by sonofmagic** [comment]
Hi！
This issue is caused by the fact that there is no exact match when replacing the class string.
Corresponding unit tests have been added and this problem has been fixed in version `1.2.4`

Thanks for your report. :)

**Comment by MarvinMiles** [comment]
Confirm! Thank you for fast response :)
