### ISSUE TITLE
tailwind css obfuscator 

### ISSUE THREAD

**Issue by madruga8** [sonofmagic/tailwindcss-mangle#4]
hello,

this project works as tailwind css obfuscator ?

i could not see the obfuscation when i runned the examples on app folder

thanks !!!

**Comment by sonofmagic** [comment]
Hello, [madruga8](https://github.com/madruga8)

Yes, this project is a tailwindcss obfuscator. But now (0.0.3) it only works in vite project. webpack plugin still has some issues to be solved. this project is in development

if you want to see the obfuscation in app folder, you can do the following steps:
1. git clone this repo
2. pnpm i
3. pnpm dev:pkg
4. cd app/vite-vue (or vite-react / vite-svelte)
5. pnpm build
6. pnpm preview

Then you will see most of tailwindcss classes are rename to `tw-*`

Thanks :)

**Comment by madruga8** [comment]
Very good project ! thanks !

**Comment by madruga8** [comment]
this example on webpack worked very well for me execept that its not mangling JS files.. just CSS+HTML

const path = require('path');
const { webpackPlugin: utwm } = require('unplugin-tailwindcss-mangle');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { merge } = require('webpack-merge');

const commonConfig = {
    mode: 'development',
    devtool: 'source-map',
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader'],
            },
            {
                test: /\.ejs$/,
                use: 'raw-loader',
            },
            {
                test: /\.html$/,
                use: 'raw-loader',
            },
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            }
        ],
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    plugins: [
        utwm(),
        new MiniCssExtractPlugin({
            filename: 'styles.css',
        }),
    ],
};

const serverConfig = {
    entry: './src/index.ts',
    output: {
        // clean: true,
        filename: 'server.bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
    target: 'node18',
};

const clientConfig = {
    entry: './src/client.ts',
    output: {
        // clean: true,
        filename: 'client.bundle.js',
        path: path.resolve(__dirname, 'dist'),
    },
};

module.exports = [
    merge(commonConfig, serverConfig),
    merge(commonConfig, clientConfig),
];

**Comment by sonofmagic** [comment]
Yes, now the webpack plugin is unable to mangling JS files , but vite plugin can.

Another difficult issue is that some ssr framework like `nextjs` .., will build multiple times for `client` and `server` side bundle.
It's hard to mangle `client side code` and `server side cide` at same time.
I am trying to find a way to solve it.  :)
